### ISSUE TITLE
01 Submission Checklist:

### ISSUE THREAD

**Issue by jtoledom1** [DeepTrv/projects-web#4]
Hello @DeepTrv! ✌️
I've been reading your code and, below you can see criteria for this exercise, plese work on it, and keep learning you are in the right way!

- [ ] Semantically correct HTML structure.
- [ ] Single-page layout with sections for education, skills, and career history.
- [ ] SEO meta tags in the head section.
- [ ] OG tags for better social media sharing.
- [ ] A favicon linked in the head section.

_Avísame si necesitas retroalimentación en español_

**Comment by jtoledom1** [comment]
There's no errors, just opportunities to be better...

Important topics you need consider:
- Plese take a look at "[semantic HTML](https://cs.fyi/guide/writing-semantic-html)" in order to avoid use only div, in fact div is used just in last instance.(clean code and accessibility)
- As possible try to use indentation (spaces)

@DeepTrv please review the pull request, and make me know if you have any doubts even if doubts are about using github.

We're here to accompany you on your learning path.
